app/models/base.py
# coding: utf-8
from sqlalchemy import Column, BigInteger, func, TIMESTAMP
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class BaseColumns:
    id = Column(BigInteger(), primary_key=True, nullable=False,
                autoincrement=True, unique=True)
    create_time = Column(TIMESTAMP, server_default=func.now(), index=True)
    update_time = Column(TIMESTAMP, server_default=func.now(), index=True)

app/models/desktop.py
from sqlalchemy import Column, Text
from sqlalchemy import String
from .base import Base, BaseColumns
from flask_security import RoleMixin


class Desktop(Base, BaseColumns, RoleMixin):
    __tablename__ = "desktops"

    name = Column(String(50), server_default='')
    description = Column(Text, server_default='')
    server = Column(String(50), server_default='')
    port = Column(String(50), server_default='')
    system = Column(String(50), server_default='')
    user = Column(String(50), server_default='')
    server_password = Column(String(50), server_default='')

app/controllers/auth_route.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.engines import db
from app.models import User, Log
from flask_login import login_required, current_user
from flask_login import login_user, logout_user, login_required
auth = Blueprint('auth', __name__, url_prefix='')
param_location = ('json', )


@auth.route('/login/user', methods=['POST', 'GET'])   # 用户登录请求处理
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        user = db.session.query(User).filter_by(email=email).first()

        if user:
            if user.password == password:
                login_user(user, remember=True)
                log = Log()
                log.user = user.name
                log.operate = '帐号登录'
                db.session.add(log)
                db.session.commit()
                return redirect(url_for('vd.index'))
            else:
                flash("密码错误，再试一次")
                return render_template('login.html')
        else:
            flash("没有此用户，检查输入")
            return render_template('login.html')
    return render_template('login.html')


@auth.route('/logout', methods=['POST', 'GET'])    # 用户登出请求处理
@login_required
def logout():
    log = Log()
    log.user = current_user.name
    log.operate = '帐号登出'
    db.session.add(log)
    db.session.commit()
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/register', methods=['POST', 'GET'])     # 用户注册请求处理
def register():
    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        password1 = request.form['password1']
        password2 = request.form['password2']

        user = db.session.query(User).filter_by(email=email).first()

        if user:
            flash(" 此邮箱已被注册")
            return render_template('register.html')

        if password1 != password2:
            flash("两次输入密码不一致")
            return render_template('register.html')

        user = User()
        user.name = name
        user.email = email
        user.password = password1
        user.role_id = 2
        db.session.add(user)
        db.session.commit()
        log = Log()
        log.user = name
        log.operate = '帐号注册'
        db.session.add(log)
        db.session.commit()
        return redirect(url_for('auth.login'))
    return render_template('register.html')

app/controllers/desktop_operate.py
import paramiko
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user
from app.models import User_Desktop, Desktop
from app.engines import db

desktop_operate = Blueprint('desktop_operate', __name__, url_prefix='')
param_location = ('json', )


@desktop_operate.route('/desktop/list')
@login_required
def desktop_list():
    desktop_id_list = db.session.query(User_Desktop.desktop_id).filter(User_Desktop.user_id == current_user.id).all()
    if desktop_id_list:
        desktop_id_list = [value[0] for value in desktop_id_list]

    desktops = db.session.query(Desktop).filter(Desktop.id.in_(desktop_id_list)).all()
    return render_template('desktop_list.html', desktops=desktops)


@desktop_operate.route('/desktop/delete/<int:desktop_id>')
def desktop_delete(desktop_id):
    desktop = db.session.query(Desktop).filter(Desktop.id == desktop_id).first()
    db.session.delete(desktop)
    db.session.commit()
    return redirect(url_for('desktop_operate.desktop_list'))


@desktop_operate.route('/desktop/add', methods=['POST', 'GET'])
def desktop_add():
    if request.method == 'POST':

        server_user = request.form['server_user']

        server_password = request.form['server_password']
        server_ip = request.form['server_ip']
        server_name = request.form['server_name']
        server_system = request.form['server_system']
        server_port = request.form['server_port']
        desktop_desc = request.form['desktop_desc']
        if server_user == '' or server_ip == '' or server_password == '':
            flash(" 检查某些字段是否为空")
            return redirect(url_for('desktop_operate.desktop_add'))

        try:
            ssh = paramiko.SSHClient()
            ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            ssh.connect(hostname=server_ip, port=22, username=server_user, password=server_password)
        except Exception as e:
            flash("服务器IP、用户名、密码可能错误")
            return redirect(url_for('desktop_operate.desktop_add'))

        desktop = Desktop()
        desktop.server_password = server_password
        desktop.user = server_user
        desktop.name = server_name
        desktop.system = server_system
        desktop.port = server_port
        desktop.server = server_ip
        desktop.description = desktop_desc
        db.session.add(desktop)
        db.session.commit()
        db.session.query(Desktop).order_by(Desktop.create_time.desc()).filter(Desktop.server == server_ip).first()
        user_desktop = User_Desktop()
        user_desktop.user_id = current_user.id
        user_desktop.desktop_id = desktop.id
        db.session.add(user_desktop)
        db.session.commit()
        return redirect(url_for('desktop_operate.desktop_list'))

    return render_template('desktop_add.html')


@desktop_operate.route('/desktop/change/<int:desktop_id>', methods=['POST', 'GET'])
def desktop_change(desktop_id):
    desktop = db.session.query(Desktop).filter(Desktop.id == desktop_id).first()
    if request.method == 'POST':

        server_user = request.form['server_user']

        server_password = request.form['server_password']
        server_ip = request.form['server_ip']
        server_name = request.form['server_name']
        server_system = request.form['server_system']
        server_port = request.form['server_port']
        desktop_desc = request.form['desktop_desc']
        if server_user == '' or server_ip == '' or server_password == '':
            flash(" 检查某些字段是否为空")
            return redirect(url_for('desktop_operate.desktop_change', desktop_id=desktop.id))

        try:
            ssh = paramiko.SSHClient()
            ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            ssh.connect(hostname=server_ip, port=22, username=server_user, password=server_password)
        except Exception as e:
            flash("服务器IP、用户名、密码可能错误")
            return redirect(url_for('desktop_operate.desktop_change', desktop_id=desktop.id))

        desktop.server_password = server_password
        desktop.user = server_user
        desktop.name = server_name
        desktop.system = server_system
        desktop.port = server_port
        desktop.server = server_ip
        desktop.description = desktop_desc
        db.session.add(desktop)
        db.session.query(Desktop).order_by(Desktop.create_time.desc()).filter(Desktop.server == server_ip).first()
        user_desktop = User_Desktop()
        user_desktop.user_id = current_user.id
        user_desktop.desktop_id = desktop.id
        db.session.add(user_desktop)
        db.session.commit()
        return redirect(url_for('desktop_operate.desktop_list'))
    return render_template('desktop_change.html', desktop=desktop)

app/controllers/log_operate.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user
from app.models import User_Desktop, Desktop, User, Log
from app.engines import db

log_operate = Blueprint('log_operate', __name__, url_prefix='')
param_location = ('json', )


@log_operate.route('/log/list')
@login_required
def log_list():
    logs = db.session.query(Log).all()

    return render_template('log_list.html', logs=logs)

app/controllers/user_info.py
from flask import Blueprint, render_template, request, flash, redirect, url_for

from datetime import datetime, timedelta
from app.models import User
from app.engines import db
from flask_login import login_required, current_user


info = Blueprint('info', __name__, url_prefix='')
param_location = ('json', )


@info.route('/info', methods=['POST', 'GET'])
@login_required
def user_info():
    if request.method == 'POST':

        user = db.session.query(User).filter(User.id == current_user.id).first()
        name = request.form['name']
        email = request.form['email']
        if name == '' or email == '':
            flash('字段不能空')
            redirect(url_for('info.user_info'))
        user.name = name
        user.email = email
        db.session.add(user)
        db.session.commit()
        flash('修改成功')

    return render_template('user_info.html')

app/controllers/user_operate.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user
from app.models import User_Desktop, Desktop, User
from app.engines import db

user_operate = Blueprint('user_operate', __name__, url_prefix='')
param_location = ('json', )


@user_operate.route('/user/list')
@login_required
def user_list():
    users = db.session.query(User).all()

    return render_template('user_list.html', users=users)


@user_operate.route('/user/delete/<int:user_id>')
def user_delete(user_id):
    user = db.session.query(User).filter(User.id == user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('user_operate.user_list'))


@user_operate.route('/user/change/<int:user_id>', methods=['POST', 'GET'])
def user_change(user_id):
    user = db.session.query(User).filter(User.id == user_id).first()
    if request.method == 'POST':

        name = request.form['name']

        email = request.form['email']
        role = request.form['role']
        if '管理' in role:
            role = 1
        else:
            role = 2
        password = request.form['password']
        if name == '' or email == '' or role == '' or password == '':
            flash(" 检查某些字段是否为空")
            return redirect(url_for('user_operate.user_change', user_id=user.id))

        user.name = name
        user.email = email
        user.role_id = int(role)
        user.password = password

        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user_operate.user_list'))
    return render_template('user_change.html', user=user)


@user_operate.route('/user/add', methods=['POST', 'GET'])
def user_add():
    if request.method == 'POST':

        name = request.form['name']

        email = request.form['email']
        role = request.form['role']
        # if '管理' in role:
        #     role = 1
        # else:
        #     role = 2
        password = request.form['password']
        if name == '' or email == '' or role == '' or password == '':
            flash(" 检查某些字段是否为空")
            return redirect(url_for('user_operate.user_change'))

        user = User()
        user.name = name
        user.email = email
        user.role_id = int(role)
        user.password = password

        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user_operate.user_list'))

    return render_template('user_add.html')

app/templates/desktop_list.html
{% extends "base.html" %}


        {% block header %}
            <header id="cm-header">
            <nav class="cm-navbar cm-navbar-primary">
                <div class="btn btn-primary md-menu-white hidden-md hidden-lg" data-toggle="cm-menu"></div>
                <div class="cm-flex">
                    {% block title %}
                    <h1>Home</h1>
                        {% endblock %}
                    <form id="cm-search" action="index.html" method="get">
                        <input type="search" name="q" autocomplete="off" placeholder="Search...">
                    </form>
                </div>
                <div class="pull-right">
                    <div id="cm-search-btn" class="btn btn-primary md-search-white" data-toggle="cm-search"></div>
                </div>

                <div class="dropdown pull-right">
                    <button class="btn btn-primary md-account-circle-white" data-toggle="dropdown"></button>
                    <ul class="dropdown-menu">

                        {% if current_user.is_authenticated %}
                        <li class="disabled text-center">
                            <a style="cursor:default;"><strong>{{ current_user.name }}</strong></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>

                        <li>
                            <a href="{{ url_for('auth.logout') }}"><i class="fa fa-fw fa-sign-out"></i> Sign out</a>
                        </li>
                        {% else %}
                        <li class="divider"></li>
                        <li>
                            <a href="{{ url_for('auth.register') }}"><i class="fa fa-fw fa-download"></i> Register</a>
                        </li>

                        <li>
                            <a href="{{ url_for('auth.login') }}"><i class="fa fa-fw fa-sign-out"></i> Sign in</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            <nav class="cm-navbar cm-navbar-default cm-navbar-slideup">
    <div class="cm-flex">
        <div class="nav-tabs-container">
            <ul class="nav nav-tabs">
                <li class="active"><a href="{{ url_for('desktop_operate.desktop_list') }}">桌面列表</a></li>
                <li><a href="{{ url_for('desktop_operate.desktop_add') }}">添加桌面</a></li>
            </ul>
        </div>
    </div>
</nav>
        </header>
        {% endblock %}
    {% block navbar %}
class="cm-no-transition cm-2-navbar"
{% endblock %}




{% block global %}
        <div id="global">
            <div class="container-fluid">


                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">当前用户所管理的所有桌面</div>
                            <div class="panel-body">
                                <table class="table table-bordered table-hover">

                                    <thead>
                                        <tr>
                                            <th>桌面序号</th>
                                            <th>创建时间</th>
                                            <th>更新时间</th>
                                            <th>桌面昵称</th>
                                            <th>桌面描述</th>
                                            <th>服务器IP</th>
                                            <th>服务器端口</th>
                                            <th>服务器系统</th>
                                            <th>服务器用户</th>
                                            <th>操作桌面</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for desktop in desktops %}
                                        <tr>
                                            <th scope="row">{{ loop.index }}</th>
                                            <td>{{ desktop.create_time|string|truncate(19, True, '') }}</td>
                                            <td>{{ desktop.update_time|string|truncate(19, True, '') }}</td>
                                            <td>{{ desktop.name }}</td>
                                            <td>{{ desktop.description }}</td>
                                            <td>{{ desktop.server }}</td>
                                            <td>{{ desktop.port }}</td>
                                            <td>{{ desktop.system }}</td>
                                            <td>{{ desktop.user }}</td>
                                            <td>
                                                <div class="btn-group">
                                                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">管理 <span class="caret"></span></button>
                                                    <ul class="dropdown-menu" role="menu">
                                                    <li><a href="{{ url_for('desktop_operate.desktop_change', desktop_id=desktop.id) }}">修改桌面</a></li>
                                                    <li><a href="{{ url_for('desktop_operate.desktop_delete', desktop_id=desktop.id) }}">删除桌面</a></li>
                                                    </ul>
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>

                </div>

            </div>
             <footer class="cm-footer"><span class="pull-left">Powered By MagicShell</span><span class="pull-right">Copyright &copy; HUANGZP 2018</span></footer>
        </div>
{% endblock %}

app/templates/desktop_panel.html
{% extends "base.html" %}


                    {% block title %}
                    <h1>虚拟桌面启动</h1>
                        {% endblock %}

{% block global %}
        <div id="global">
            <div class="container-fluid">
               <div class="row cm-fix-height">

                   {% for desktop in desktops %}
                 <a href="{{ url_for('panel.desktop_file', desktop_id=desktop.id) }}">   <div class="col-sm-6">
                        <div class="panel panel-default">
                            <div class="panel-heading"><strong>{{ desktop.name }}</strong> </div>

                                <div class="panel-body">

                                <h3 style="margin-top:0"> <small>Server Ip：{{ desktop.server }}</small> </h3>
                              <h3>  <small>  Server System：{{ desktop.system }}</small></h3>
                                 <h3>  <small> Server User：{{ desktop.user }}</small></h3>
                                  <h3> <small> Server Description：{{ desktop.description }}</small></h3>



                                </div>

                            </div>
                        </div></a>

                   {% endfor %}


                </div>

            </div>
        </div>
{% endblock %}

app/templates/file_cat.html
{% extends "base.html" %}


                    {% block title %}
                    <h1>文件查看</h1>
                        {% endblock %}

{% block global %}
        <div id="global">
            <div class="container-fluid">
                <div class="panel panel-default">
                    <div class="panel-body"> <h1 style="margin:10px;">{{ text|safe }}</h1> </div>
                </div>
            </div>

        </div>
{% endblock %}

app/templates/user_add.html
{% extends "base.html" %}


        {% block header %}
            <header id="cm-header">
            <nav class="cm-navbar cm-navbar-primary">
                <div class="btn btn-primary md-menu-white hidden-md hidden-lg" data-toggle="cm-menu"></div>
                <div class="cm-flex">
                    {% block title %}
                    <h1>Home</h1>
                        {% endblock %}
                    <form id="cm-search" action="index.html" method="get">
                        <input type="search" name="q" autocomplete="off" placeholder="Search...">
                    </form>
                </div>
                <div class="pull-right">
                    <div id="cm-search-btn" class="btn btn-primary md-search-white" data-toggle="cm-search"></div>
                </div>

                <div class="dropdown pull-right">
                    <button class="btn btn-primary md-account-circle-white" data-toggle="dropdown"></button>
                    <ul class="dropdown-menu">

                        {% if current_user.is_authenticated %}
                        <li class="disabled text-center">
                            <a style="cursor:default;"><strong>{{ current_user.name }}</strong></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>

                        <li>
                            <a href="{{ url_for('auth.logout') }}"><i class="fa fa-fw fa-sign-out"></i> Sign out</a>
                        </li>
                        {% else %}
                        <li class="divider"></li>
                        <li>
                            <a href="{{ url_for('auth.register') }}"><i class="fa fa-fw fa-download"></i> Register</a>
                        </li>

                        <li>
                            <a href="{{ url_for('auth.login') }}"><i class="fa fa-fw fa-sign-out"></i> Sign in</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            <nav class="cm-navbar cm-navbar-default cm-navbar-slideup">
    <div class="cm-flex">
        <div class="nav-tabs-container">
            <ul class="nav nav-tabs">
                <li><a href="{{ url_for('user_operate.user_list') }}">用户列表</a></li>
                <li class="active"><a href="{{ url_for('user_operate.user_add') }}">添加用户</a></li>
            </ul>
        </div>
    </div>
</nav>
        </header>
        {% endblock %}
    {% block navbar %}
class="cm-no-transition cm-2-navbar"
{% endblock %}




{% block global %}
        <div id="global">
            <div class="container-fluid">


                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">修改用户信息信息</div>
                            <div class="panel-body">

    <div class="col-sm-6 col-md-4 col-lg-3" style="margin:40px auto; float:none;">
                                             {% for message in get_flashed_messages() %}
                             <div class="alert alert-warning">
                             <button type="button" class="close" data-dismiss="alert">&times;</button>
                             {{ message }}
                             </div>
                    {% endfor %}
     <form method="post" action="{{ url_for('user_operate.user_add') }}" >
	<div class="col-xs-12">
                  <div class="form-group">
	    <div class="input-group">
	      <div class="input-group-addon"><i class="fa fa-fw fa-child"></i></div>
	      <input type="text" name="name" class="form-control" placeholder="用户昵称"">
	    </div>
          </div>
          <div class="form-group">
	    <div class="input-group">
	      <div class="input-group-addon"><i class="fa fa-fw fa-user"></i></div>
	      <input type="text" name="email" class="form-control" placeholder="用户邮箱"">
	    </div>
          </div>
          <div class="form-group">
	    <div class="input-group">
	      <div class="input-group-addon"><i class="fa fa-fw fa-lock"></i></div>
	      <input type="password" name="password" class="form-control" placeholder="用户密码" >
	    </div>
          </div>
                  <div class="form-group">
	    <div class="input-group">
	      <div class="input-group-addon"><i class="fa fa-fw fa-cloud"></i></div>
{#	      <input type="text" name="role" class="form-control" placeholder="用户角色" value="普通用户">#}
                                <select name="role" class=" form-control" >
                                        <option value="0">普通用户</option>
                                        <option value="1">管理员</option>

                                </select>
	    </div>
          </div>

        </div>
	<div class="col-xs-6">
         <a href="{{ url_for('user_operate.user_list') }}"> <button type="button" class="btn btn-block btn-default">放弃</button> </a>
	</div><div class="col-xs-6">
          <button type="submit" class="btn btn-block btn-primary">提交</button>
        </div>
      </form>
    </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
             <footer class="cm-footer"><span class="pull-left">Powered By MagicShell</span><span class="pull-right">Copyright &copy; HUANGZP 2018</span></footer>
        </div>
{% endblock %}

app/templates/user_list.html
{% extends "base.html" %}


        {% block header %}
            <header id="cm-header">
            <nav class="cm-navbar cm-navbar-primary">
                <div class="btn btn-primary md-menu-white hidden-md hidden-lg" data-toggle="cm-menu"></div>
                <div class="cm-flex">
                    {% block title %}
                    <h1>Home</h1>
                        {% endblock %}
                    <form id="cm-search" action="index.html" method="get">
                        <input type="search" name="q" autocomplete="off" placeholder="Search...">
                    </form>
                </div>
                <div class="pull-right">
                    <div id="cm-search-btn" class="btn btn-primary md-search-white" data-toggle="cm-search"></div>
                </div>

                <div class="dropdown pull-right">
                    <button class="btn btn-primary md-account-circle-white" data-toggle="dropdown"></button>
                    <ul class="dropdown-menu">

                        {% if current_user.is_authenticated %}
                        <li class="disabled text-center">
                            <a style="cursor:default;"><strong>{{ current_user.name }}</strong></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>

                        <li>
                            <a href="{{ url_for('auth.logout') }}"><i class="fa fa-fw fa-sign-out"></i> Sign out</a>
                        </li>
                        {% else %}
                        <li class="divider"></li>
                        <li>
                            <a href="{{ url_for('auth.register') }}"><i class="fa fa-fw fa-download"></i> Register</a>
                        </li>

                        <li>
                            <a href="{{ url_for('auth.login') }}"><i class="fa fa-fw fa-sign-out"></i> Sign in</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            <nav class="cm-navbar cm-navbar-default cm-navbar-slideup">
    <div class="cm-flex">
        <div class="nav-tabs-container">
            <ul class="nav nav-tabs">
                <li class="active"><a href="{{ url_for('user_operate.user_list') }}">用户列表</a></li>
                                <li><a href="{{ url_for('user_operate.user_add') }}">添加用户</a></li>
            </ul>
        </div>
    </div>
</nav>
        </header>
        {% endblock %}
    {% block navbar %}
class="cm-no-transition cm-2-navbar"
{% endblock %}




{% block global %}
        <div id="global">
            <div class="container-fluid">


                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">管理系统所有用户</div>
                            <div class="panel-body">
                                <table class="table table-bordered table-hover">

                                    <thead>
                                        <tr>
                                            <th>用户序号</th>
                                            <th>创建时间</th>
                                            <th>更新时间</th>
                                            <th>用户昵称</th>
                                            <th>用户邮箱</th>
                                            <th>用户角色</th>
                                            <th>用户状态</th>
                                            <th>操作用户</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for user in users %}
                                        <tr>
                                            <th scope="row">{{ loop.index }}</th>
                                            <td>{{ user.create_time|string|truncate(19, True, '') }}</td>
                                            <td>{{ user.update_time|string|truncate(19, True, '') }}</td>
                                            <td>{{ user.name }}</td>
                                            <td>{{ user.email }}</td>
                                            <td>{% if user.role_id == 1 %} 管理员 {% else %} 普通用户 {% endif %}</td>
                                            <td>已激活</td>

                                            <td>
                                                <div class="btn-group">
                                                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">管理 <span class="caret"></span></button>
                                                    <ul class="dropdown-menu" role="menu">
                                                    <li><a href="{{ url_for('user_operate.user_change', user_id=user.id) }}">修改用户</a></li>
                                                    <li><a href="{{ url_for('user_operate.user_delete', user_id=user.id) }}">删除用户</a></li>
                                                    </ul>
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>

                </div>

            </div>
             <footer class="cm-footer"><span class="pull-left">Powered By MagicShell</span><span class="pull-right">Copyright &copy; HUANGZP 2018</span></footer>
        </div>
{% endblock %}